Map<int, String> turnIcon = {
  1: 'assets/icons/navigation_straight.png',
  2: 'assets/icons/navigation_turn_left.png',
  3: 'assets/icons/navigation_turn_right.png',
  4: 'assets/icons/navigation_turn11.png',
  5: 'assets/icons/navigation_turn1.png',
  10: 'assets/icons/navigation_u_turn.png',
  20: 'assets/icons/navigation_straight.png',
  22: 'assets/icons/navigation_straight.png',
  31: 'assets/icons/navigation_round1.png',
  32: '동그란 도로 돌아서 우회전',
  34: 'assets/icons/navigation_round7.png',
  35: '동그란 도로 돌아서 좌회전',
  36: 'assets/icons/navigation_round11.png',
  36: '동그란 도로 돌아서 직진',
  39: 'assets/icons/navigation_straight.png',
  39: 'assets/icons/navigation_straight.png',
  48: 'assets/icons/marker_start.png',
  41: 'assets/icons/marker_destination.png',
};
