// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_86iQ0rgxYTNg3vAxU5PBt-eXla8q1w',
    appId: '1:93312283448:web:ca183b701def46b64107cd',
    messagingSenderId: '93312283448',
    projectId: 'riding-partner-flutter',
    authDomain: 'riding-partner-flutter.firebaseapp.com',
    databaseURL: 'https://riding-partner-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riding-partner-flutter.appspot.com',
    measurementId: 'G-5JT3M4K9C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CVWEZ-Vs-NUFLmoNDwGuoD4_Z4vd46w',
    appId: '1:93312283448:android:994d176c6e50301e4107cd',
    messagingSenderId: '93312283448',
    projectId: 'riding-partner-flutter',
    databaseURL: 'https://riding-partner-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riding-partner-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn1JwEpwqkM0oj9ZBNQXlZ3nOsv7yVXPg',
    appId: '1:93312283448:ios:7e84bc79d44000a54107cd',
    messagingSenderId: '93312283448',
    projectId: 'riding-partner-flutter',
    databaseURL: 'https://riding-partner-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riding-partner-flutter.appspot.com',
    androidClientId: '93312283448-0rmtj9psqt5agq5evi50p6ivd29dp2ki.apps.googleusercontent.com',
    iosClientId: '93312283448-umnkpg0cqanrksa12brshebh4fgumlqh.apps.googleusercontent.com',
    iosBundleId: 'com.neighbor.ridingpartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn1JwEpwqkM0oj9ZBNQXlZ3nOsv7yVXPg',
    appId: '1:93312283448:ios:8d58951ef8bcd8ce4107cd',
    messagingSenderId: '93312283448',
    projectId: 'riding-partner-flutter',
    databaseURL: 'https://riding-partner-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'riding-partner-flutter.appspot.com',
    androidClientId: '93312283448-0rmtj9psqt5agq5evi50p6ivd29dp2ki.apps.googleusercontent.com',
    iosBundleId: 'com.neighbor.ridingpartner.ridingpartnerFlutter',
  );
}
